# Generated by Django 5.2.5 on 2025-08-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleWeaver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('fotbal', 'Fotbal'), ('tenis', 'Tenis'), ('handbal', 'Handbal'), ('alte', 'Alte sporturi')], default='alte', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
