# Generated by Django 5.2.5 on 2025-08-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleWeaver', '0002_article_category_article_image_url_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pub', 'Published')], default='pub', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('fotbal-intern', 'Fotbal Intern'), ('fotbal-extern', 'Fotbal Extern'), ('tenis', 'Tenis'), ('alte', 'Alte Sporturi')], default='alte', max_length=50),
        ),
    ]
